

radar_softdegrade_notboth:

  config:
    distance_metric: NA
    aggregate_method: entropy
    seq_select_method: safe_pow_gate
    num_out: 10
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    corrupt_imp_weights: False
    num_epochs: 1
    system_seed: 108

  model_name: radar_softdegrade
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: testing_logging
  secret_key:

radar_softdegrade_use_both:

  config:
    distance_metric: NA
    aggregate_method: entropy
    seq_select_method: safe_pow_gate
    num_out: 10
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    corrupt_imp_weights: False
    num_epochs: 60
    system_seed: 580316

  model_name: radar_softdegrade
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: Powergate_nonFiLM_APE
  secret_key: 


radar_softanchor_v1:

  config:
    aggregate_method: norm_softmax
    distance_metric: NA
    seq_select_method: weighted_sum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 0.0
    corrupt_imp_weights: False
    num_epochs: 60
    num_out: 10
    system_seed: 580316

  model_name: radar_softanchor_v1
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: SoftAnchor_v1_ViT_NoAPE
  secret_key: 


radar_softanchor_v2:

  config:
    aggregate_method: norm_softmax
    distance_metric: NA
    seq_select_method: weighted_sum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    corrupt_imp_weights: False
    num_epochs: 60
    num_out: 10
    system_seed: 580316

  model_name: radar_softanchor_v2
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: SoftAnchor_v2_ViT
  secret_key: 


radar_softanchor_loo:

  config:
    aggregate_method: norm_softmax
    distance_metric: NA
    seq_select_method: loo_weighsum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    corrupt_imp_weights: False
    num_epochs: 8
    num_out: 10
    system_seed: 12345

  model_name: radar_softanchor_v1 # This is TBD whether V1 or V2
  team_name: amith-adiraju-self
  project_name: hybrid_posenc_test_preNormINJ_v2
  run_name: aggregate_FiLMinj_LOOsum_sharpness
  secret_key: 

radar_softanchor_v1_random:
  config:
    exp_seed: 108
    num_out: 10
    use_both: True
    perc_ape: 1.0
    num_epochs: 60
    system_seed: 580316

  model_name: radar_softanchor_v1_random
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: SoftAnchor_v1_GaussianFiLM
  secret_key: 
  
  
single_peg_cpvt:
  config:
    num_out: 10
    perc_ape: 0.0
    k: 27
    num_epochs: 60
    system_seed: 108

  model_name: single_peg_cpvt
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_Ablations
  run_name: SinglePEG_NoAPE
  secret_key: 