
radar_softdegrade_notboth:

  config:
    distance_metric: NA
    aggregate_method: entropy
    seq_select_method: safe_pow_gate
    num_out: 10
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    use_both: False    
    num_epochs: 8
    system_seed: 108

  model_name: radar_softdegrade
  team_name: amith-adiraju-self
  project_name: 
  run_name: 
  secret_key: 

radar_softdegrade_use_both:

  config:
    distance_metric: NA
    aggregate_method: entropy
    seq_select_method: safe_pow_gate
    num_out: 10
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    use_both: True    
    num_epochs: 8
    system_seed: 12345

  model_name: radar_softdegrade
  team_name: amith-adiraju-self
  project_name: hybrid_posenc_test_preNormINJ_v2
  run_name: aggr_safepowgate_B_nonFiLM
  secret_key: 


radar_softanchor_v1:

  config:
    aggregate_method: norm_softmax
    distance_metric: NA
    seq_select_method: weighted_sum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    num_epochs: 8
    num_out: 10
    system_seed: 108

  model_name: radar_softanchor_v1
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_test
  run_name: SoftAnchorViT
  secret_key: 


radar_softanchor_v2:

  config:
    aggregate_method: norm_softmax
    distance_metric: NA
    seq_select_method: weighted_sum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    num_epochs: 8
    num_out: 10
    system_seed: 108

  model_name: radar_softanchor_v2
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_test
  run_name: SoftAnchorViT
  secret_key: 


radar_softanchor_loo:

  config:
    aggregate_method: norm_softmax
    distance_metric: NA
    seq_select_method: loo_weighsum
    add_coordinates: False
    K: 3
    aggregate_dim: 2
    norm_type: 2
    return_anchors: True
    perc_ape: 1.0
    num_epochs: 8
    num_out: 10
    system_seed: 12345

  model_name: radar_softanchor_v1 # This is TBD whether V1 or V2
  team_name: amith-adiraju-self
  project_name: hybrid_posenc_test_preNormINJ_v2
  run_name: aggregate_FiLMinj_LOOsum_sharpness
  secret_key: 

radar_softanchor_v1_random:
  config:
    exp_seed: 108
    num_out: 10
    use_both: True
    num_epochs: 8
    system_seed: 108

  model_name: radar_softanchor_v1_random
  team_name: amith-adiraju-self
  project_name: 
  run_name: 
  secret_key:

static_pos_enc:

  config:
    num_out: 10 
    system_seed: 1109711497
    num_epochs: 300

  model_name: static
  team_name: amith-adiraju-self
  project_name: ViT_RADAR_benchmarks
  run_name: BaselineViT
  secret_key: 
  
  
